/** 1688 采购运营 Demo 常量 */

export const ALIBABA1688_OPERATOR = { name: '赵磊', role: '1688 采购' }

export const PURCHASE_ORDER_STATUSES = {
  pending_payment: { label: '待付款', type: 'warning' },
  pending_shipment: { label: '待发货', type: 'danger' },
  pending_receive: { label: '待收货', type: 'primary' },
  completed: { label: '已完成', type: 'success' },
}

export const SUPPLIER_ALERT_TYPES = {
  price_increase: { label: '涨价预警', type: 'danger' },
  delivery_delay: { label: '交期延误', type: 'warning' },
  moq_change: { label: '起订量变更', type: 'info' },
  delay: { label: '到货延期', type: 'warning' },
  stockout: { label: '缺货', type: 'danger' },
  quality: { label: '质量异常', type: 'danger' },
  other: { label: '其他', type: 'info' },
}

export const PURCHASE_ORDER_TEMPLATES = [
  {
    productName: '双人帐篷 210T 涤纶',
    sku: 'YT-TENT-210T',
    supplierName: '义乌市恒野户外用品厂',
    quantity: 800,
    unitPrice: 68.5,
    linkedPlatform: 'Temu',
    status: 'pending_payment',
  },
  {
    productName: '碳纤维登山杖 2 节',
    sku: 'YT-POLE-CF2',
    supplierName: '宁海锐峰杖业',
    quantity: 1200,
    unitPrice: 23.8,
    linkedPlatform: 'Temu',
    status: 'pending_shipment',
  },
  {
    productName: '户外睡袋 0°C 信封式',
    sku: 'YT-BAG-0C',
    supplierName: '扬州羽绒制品厂',
    quantity: 500,
    unitPrice: 95,
    linkedPlatform: 'AliExpress',
    status: 'pending_shipment',
  },
  {
    productName: '太阳能露营灯',
    sku: 'YT-LAMP-SOL',
    supplierName: '深圳光野电子',
    quantity: 600,
    unitPrice: 18.6,
    linkedPlatform: 'Temu',
    status: 'pending_receive',
  },
  {
    productName: '折叠露营椅',
    sku: 'YT-CHAIR-FLD',
    supplierName: '永康市乐途休闲',
    quantity: 400,
    unitPrice: 42,
    linkedPlatform: '独立站',
    status: 'pending_receive',
  },
  {
    productName: '防潮垫 180×55cm',
    sku: 'YT-MAT-180',
    supplierName: '青岛泡沫科技',
    quantity: 1000,
    unitPrice: 12.5,
    linkedPlatform: 'AliExpress',
    status: 'completed',
  },
]

export const SUPPLIER_ALERT_TEMPLATES = [
  {
    type: 'price_increase',
    supplierName: '宁海锐峰杖业',
    productName: '碳纤维登山杖 2 节',
    detail: '单价由 ¥22.5 上调至 ¥23.8（+5.8%）',
    severity: 'high',
  },
  {
    type: 'delivery_delay',
    supplierName: '义乌市恒野户外用品厂',
    productName: '双人帐篷 210T 涤纶',
    detail: '承诺 3 天发货，已超期 1 天未出库',
    severity: 'high',
  },
  {
    type: 'moq_change',
    supplierName: '深圳光野电子',
    productName: '太阳能露营灯',
    detail: '起订量由 300 件调整为 500 件',
    severity: 'medium',
  },
]

export const PURCHASE_ORDERS_SEED = [
  {
    id: 'po_1688_1',
    storeId: 'demo_1688_1',
    orderNo: 'CG20260624001',
    productName: '双人帐篷 210T 涤纶',
    sku: 'YT-TENT-210T',
    supplierName: '义乌市恒野户外用品厂',
    quantity: 800,
    unitPrice: 68.5,
    amount: 54800,
    linkedPlatform: 'Temu',
    status: 'pending_payment',
    createdAt: '2026-06-24 09:12:00',
    payDeadline: '2026-06-24 18:00:00',
    expectedShipAt: '2026-06-27',
  },
  {
    id: 'po_1688_2',
    storeId: 'demo_1688_1',
    orderNo: 'CG20260624002',
    productName: '碳纤维登山杖 2 节',
    sku: 'YT-POLE-CF2',
    supplierName: '宁海锐峰杖业',
    quantity: 1200,
    unitPrice: 23.8,
    amount: 28560,
    linkedPlatform: 'Temu',
    status: 'pending_shipment',
    createdAt: '2026-06-23 14:30:00',
    payDeadline: '',
    expectedShipAt: '2026-06-25',
    paidAt: '2026-06-23 15:00:00',
  },
  {
    id: 'po_1688_3',
    storeId: 'demo_1688_1',
    orderNo: 'CG20260624003',
    productName: '太阳能露营灯',
    sku: 'YT-LAMP-SOL',
    supplierName: '深圳光野电子',
    quantity: 600,
    unitPrice: 18.6,
    amount: 11160,
    linkedPlatform: 'Temu',
    status: 'pending_receive',
    createdAt: '2026-06-22 10:00:00',
    expectedShipAt: '2026-06-24',
    shippedAt: '2026-06-23 16:20:00',
    logisticsNo: 'SF168824001',
  },
  {
    id: 'po_1688_4',
    storeId: 'demo_1688_2',
    orderNo: 'CG20260624004',
    productName: '户外睡袋 0°C 信封式',
    sku: 'YT-BAG-0C',
    supplierName: '扬州羽绒制品厂',
    quantity: 500,
    unitPrice: 95,
    amount: 47500,
    linkedPlatform: 'AliExpress',
    status: 'pending_shipment',
    createdAt: '2026-06-24 08:45:00',
    paidAt: '2026-06-24 09:00:00',
    expectedShipAt: '2026-06-26',
  },
  {
    id: 'po_1688_5',
    storeId: 'demo_1688_2',
    orderNo: 'CG20260624005',
    productName: '折叠露营椅',
    sku: 'YT-CHAIR-FLD',
    supplierName: '永康市乐途休闲',
    quantity: 400,
    unitPrice: 42,
    amount: 16800,
    linkedPlatform: '独立站',
    status: 'pending_receive',
    createdAt: '2026-06-21 11:20:00',
    shippedAt: '2026-06-22 09:00:00',
    logisticsNo: 'YT168824002',
  },
]

export const SUPPLIER_ALERTS_SEED = [
  {
    id: 'sa_1688_1',
    storeId: 'demo_1688_1',
    type: 'price_increase',
    supplierName: '宁海锐峰杖业',
    productName: '碳纤维登山杖 2 节',
    sku: 'YT-POLE-CF2',
    detail: '单价由 ¥22.5 上调至 ¥23.8（+5.8%）',
    severity: 'high',
    reportedAt: '2026-06-24 10:30:00',
    resolved: false,
  },
  {
    id: 'sa_1688_2',
    storeId: 'demo_1688_1',
    type: 'delivery_delay',
    supplierName: '义乌市恒野户外用品厂',
    productName: '双人帐篷 210T 涤纶',
    sku: 'YT-TENT-210T',
    detail: '承诺 3 天发货，已超期 1 天未出库',
    severity: 'high',
    reportedAt: '2026-06-24 09:00:00',
    resolved: false,
  },
  {
    id: 'sa_1688_3',
    storeId: 'demo_1688_2',
    type: 'moq_change',
    supplierName: '深圳光野电子',
    productName: '太阳能露营灯',
    sku: 'YT-LAMP-SOL',
    detail: '起订量由 300 件调整为 500 件',
    severity: 'medium',
    reportedAt: '2026-06-23 16:00:00',
    resolved: false,
  },
]
