/** Temu 全托管官方仓 SKU 原始数据（亿拓户外 Demo） */
export const TEMU_PRODUCTS_RAW = [
  {
    sku: 'YT-T001',
    storeId: 'demo_temu_1',
    name: '轻量双人徒步帐篷 3-4人',
    sellingPrice: 189.9,
    costPrice: 78.0,
    platformFeeRate: 0.15,
    logisticsFee: 12.5,
    officialStock: 420,
    localStock: 2800,
    daysWithoutSale: 0,
    dailySales: 328,
    salesLast7Days: [180, 210, 245, 268, 290, 310, 328],
    category: '帐篷',
    owner: '王一鸣',
  },
  {
    sku: 'YT-T002',
    storeId: 'demo_temu_1',
    name: '四季露营睡袋 -10℃',
    sellingPrice: 99.0,
    costPrice: 42.0,
    platformFeeRate: 0.15,
    logisticsFee: 8.5,
    officialStock: 1860,
    localStock: 3200,
    daysWithoutSale: 5,
    dailySales: 86,
    salesLast7Days: [78, 82, 84, 85, 86, 87, 86],
    category: '睡袋',
    owner: '王一鸣',
  },
  {
    sku: 'YT-T003',
    storeId: 'demo_temu_1',
    name: '碳纤维登山杖一对',
    sellingPrice: 59.9,
    costPrice: 28.0,
    platformFeeRate: 0.15,
    logisticsFee: 6.2,
    officialStock: 280,
    localStock: 1500,
    daysWithoutSale: 0,
    dailySales: 142,
    salesLast7Days: [52, 58, 65, 88, 110, 128, 142],
    category: '登山杖',
    owner: '王一鸣',
  },
  {
    sku: 'YT-T004',
    storeId: 'demo_temu_1',
    name: 'USB 充电头灯套装',
    sellingPrice: 39.9,
    costPrice: 14.5,
    platformFeeRate: 0.15,
    logisticsFee: 4.8,
    officialStock: 920,
    localStock: 2400,
    daysWithoutSale: 3,
    dailySales: 118,
    salesLast7Days: [48, 62, 78, 92, 105, 112, 118],
    category: '户外照明',
    owner: '王一鸣',
  },
  {
    sku: 'YT-T005',
    storeId: 'demo_temu_2',
    name: '折叠露营椅',
    sellingPrice: 45.0,
    costPrice: 38.5,
    platformFeeRate: 0.15,
    logisticsFee: 7.2,
    officialStock: 1150,
    localStock: 600,
    daysWithoutSale: 32,
    dailySales: 3,
    salesLast7Days: [5, 4, 4, 3, 3, 3, 3],
    category: '运动配件',
    owner: '王一鸣',
    listingStatus: 'offline',
  },
  {
    sku: 'YT-T006',
    storeId: 'demo_temu_2',
    name: '便携燃气炉头',
    sellingPrice: 68.0,
    costPrice: 58.0,
    platformFeeRate: 0.15,
    logisticsFee: 8.0,
    officialStock: 680,
    localStock: 1200,
    daysWithoutSale: 18,
    dailySales: 12,
    salesLast7Days: [18, 15, 14, 13, 12, 12, 12],
    category: '露营炊具',
    owner: '王一鸣',
  },
  {
    sku: 'YT-T007',
    storeId: 'demo_temu_2',
    name: '防水冲锋衣男款',
    sellingPrice: 149.0,
    costPrice: 62.0,
    platformFeeRate: 0.15,
    logisticsFee: 10.5,
    officialStock: 2100,
    localStock: 500,
    daysWithoutSale: 47,
    dailySales: 0,
    salesLast7Days: [0, 0, 0, 0, 0, 0, 0],
    category: '户外服饰',
    owner: '王一鸣',
    listingStatus: 'offline',
  },
  {
    sku: 'YT-T008',
    storeId: 'demo_temu_2',
    name: '太阳能露营马灯',
    sellingPrice: 76.0,
    costPrice: 32.0,
    platformFeeRate: 0.15,
    logisticsFee: 7.5,
    officialStock: 180,
    localStock: 960,
    daysWithoutSale: 8,
    dailySales: 45,
    salesLast7Days: [38, 40, 42, 43, 44, 45, 45],
    category: '户外照明',
    owner: '王一鸣',
  },
]

export const LISTING_STATUS = {
  online: { label: '在线', type: 'success' },
  offline: { label: '已下架', type: 'info' },
}

export const SLOW_MOVING_THRESHOLDS = [
  { days: 15, label: '15 日未动销', level: 'caution', tagType: 'warning' },
  { days: 30, label: '30 日未动销', level: 'warning', tagType: 'danger' },
  { days: 45, label: '45 日未动销', level: 'critical', tagType: 'danger' },
]

export const RESTOCK_CONFIG = {
  /**
   * 与 Java TemuWarningServiceImpl.calcReplenish 对齐：
   * dailyAdj = (s7/7*0.7 + s30/30*0.3) * trend；warningDays = lead + safetyBuffer；
   * 覆盖 < warningDays 则需补货；目标库存 = dailyAdj * targetCoverDays。
   */
  leadTimeDays: 7,
  safetyBufferDays: 3,
  targetCoverDays: 15,
  demandWeight7: 0.7,
  demandWeight30: 0.3,
  trendMin: 0.8,
  trendMax: 1.5,
  /** @deprecated 仅兼容旧文案；告警阈值请用 leadTimeDays + safetyBufferDays */
  safetyDays: 10,
  /** 当日 / 7 日均 ≥ 此倍数，且当日销量 ≥ hotMinDailySales */
  hotSurgeRatio: 1.5,
  /** 真实店铺日销可能很小；用相对增幅为主，最低 1 件即可参与爆款判定 */
  hotMinDailySales: 1,
}

export const HOT_BROADCASTS = [
  {
    id: 1,
    time: '2026-06-24 11:20',
    sku: 'YT-T001',
    name: '轻量双人徒步帐篷 3-4人',
    dailySales: 328,
    avg7DayDaily: 231.6,
    surgeRatio: 1.42,
    operator: '王一鸣',
    readBy: ['李婷', '张强'],
  },
  {
    id: 2,
    time: '2026-06-24 09:15',
    sku: 'YT-T003',
    name: '碳纤维登山杖一对',
    dailySales: 142,
    avg7DayDaily: 77.6,
    surgeRatio: 1.83,
    operator: '王一鸣',
    readBy: ['李婷'],
  },
]

export const TEMU_OPERATOR = { name: '王一鸣', role: 'Temu 运营' }
